apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  annotations:
    'github.com/project-slug': ajay-infracloud/hello-world
    'backstage.io/kubernetes-id': 'app.kubernetes.io/instance=hello-world'
    'argocd/app-name': 'hello-world'
spec:
  type: service
  lifecycle: unknown
  owner: guests
